### ISSUE TITLE
no showing control/option/command on osx

### ISSUE THREAD

**Issue by maxandersen** [DaveJarvis/kmcaster#14]
running on osx and it would make sense ctrl / alt is command / option instead.

**Comment by DaveJarvis** [comment]
See my [other comment](https://github.com/DaveJarvis/kmcaster/issues/15#issuecomment-939349818), which is somewhat related. Since I don't have OSX, I cannot easily figure out what's going on.

This isn't a simple matter of mapping key codes. There would need to be a new key added to the GUI for the "option" and/or "command" key.

PR welcome.

**Comment by DaveJarvis** [comment]
@maxandersen please try with version 2.0.0 and re-open if the problem persists.

**Comment by maxandersen** [comment]
tried latest version and it still shows up with alt/ctrl and not showing anything when control/option/command pressed.

is there an option I need to specify somewhere to enable it?

**Comment by DaveJarvis** [comment]
There's no option. We'll probably need another map and condition to check for IS_OS_MACOS to defer to the additional raw/key code map.
